# Generated by Django 4.1.7 on 2023-04-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default='ff4b27a7cf39406ba8a8385f2a7a06c9', max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(default='<django.db.models.fields.CharField><django.db.models.fields.CharField>', max_length=20)),
                ('password', models.CharField(max_length=120)),
                ('verified', models.BooleanField(default=False)),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
