# Generated by Django 4.1.7 on 2023-04-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_id_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('otp_value', models.IntegerField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='b85ab4ba63c54e5389d9be440edcdd63', max_length=36, primary_key=True, serialize=False),
        ),
    ]
