# Generated by Django 4.1.7 on 2023-04-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_date_of_creation_otp_created_at_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='dbaa5b35bd5b4160959b5764f1bb645b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
