# Generated by Django 4.1.7 on 2023-04-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_otp_created_at_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='3ff39cc801d841e88a04d266673a0fb5', max_length=36, primary_key=True, serialize=False),
        ),
    ]
