# Generated by Django 4.1.7 on 2023-04-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_otp_status_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='caa3c76f560f4a9b80b62f9aaf375bdb', max_length=36, primary_key=True, serialize=False),
        ),
    ]
