# Generated by Django 4.1.7 on 2023-04-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='2289ed8f8c0a46049ca5450a739dd3ba', max_length=36, primary_key=True, serialize=False),
        ),
    ]
