# Generated by Django 4.1.7 on 2023-04-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_joining',
            new_name='joined_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
