# Generated by Django 4.1.7 on 2023-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_title_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='responded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
