# Generated by Django 4.1.7 on 2023-04-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projectmember_responded_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectSection',
        ),
    ]
